config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root  "employees#index"
  resources :employees do
  	resources :pay_periods
  end

  get 'create' => "employees#new"

  resource :session

  get "signin" => "sessions#new"

  resource :work_hours

  resources :admins do
    member do
      get :work_groups
      get :time_sheets
    end
  end

  get 'admins/:admin_id/work_groups/:id', to: 'admins#select_employee', as: "admin_work_groups"
  get 'admins/:admin_id/employee/:id', to: 'admins#select_pay_period', as: "select_employee_pay_period"
  resources :work_groups

  #patch 'admins/:admin_id/pay_period/:id', to: 'admins#admin_get_pay_period', as: "admin_get_pay_period"
  get 'admins/:admin_id/pay_period/:id', to: 'admins#admin_view_pay_period', as: "admin_view_pay_period"
end

app/views/admins/admin_view_pay_period.html.erb
<h3> <%= @employee.first_name %> <%= @employee.last_name %> </h3>
<h4> From <%= @pay_period.start_date %> to <%= @pay_period.end_date %>
<hr>
<% @days.each do |work_day| %>
  <div>
    <%= work_day.date %> <%= work_day.day %>
    <br/>
    <% if work_day.regular %>
      Regular Hours: <%= work_day.regular %>
      <br/>
    <% end %>
    <% if work_day.over_time %>
      Over-Time Hours: <%= work_day.over_time %>
      <br/>
    <% end %>
    <% if work_day.sick_leave %>
      Sick-leave Hours: <%= work_day.sick_leave %>
      <br/>
    <% end %>
    <% if work_day.vacation %>
      Vacation Hours: <%= work_day.vacation %>
      <br/>
    <% end %>
    <% if work_day.non_paid_leave %>
      Non Paid Leave Hours: <%= work_day.non_paid_leave %>
      <br/>
    <% end %>
    <% if work_day.daily_total %>
      Total Daily Hours: <%= work_day.daily_total %>
    <% end %>
  </div>
  <hr>
<% end %>
Pay Period Totals:

app/views/admins/select_employee.html.erb
<h3>
  Work Group: <%= @work_group.name %>
</h3>

<div class="container">
<%= form_for @work_group do |f| %>

 <div class="form-group">
   <%= f.label "Select Employee" %>
   <%= f.select :employees, options_for_select(generate_employee_roster(@work_group)), class: 'form-control'%>
 </div>
 <div>
   <%= f.submit 'view pay period', class: 'btn btn-primary btn-sm' %>
 </div>
<% end %>
</div>

app/views/admins/select_pay_period.html.erb
<h3>Pay periods for: <%= @employee.first_name %> <%= @employee.last_name %> </h3>
<div class="container">
<%= form_for @employee, url: admin_view_pay_period_path(@admin,@employee), method: :get do |f| %>

 <div class="form-group">
   <%= f.label "Select Pay Period" %>
   <%= f.select :pay_periods, options_for_select(generate_pay_periods(@employee)), class: 'form-control'%>
 </div>
 <div>
   <%= f.submit 'Edit/View Timesheet', class: 'btn btn-primary btn-sm' %>
 </div>
<% end %>
</div>

app/views/admins/show.html.erb
 <header>
   <h3>Admin portal for: <%= @admin.first_name %> <%= @admin.last_name %>
   </h3>
   <br/>
   <h4>
   <%= @admin.first_name %>'s Work Groups:
   </h4>
   <% @wgs.each do |work_group| %>
      <%= link_to work_group.name, admin_work_groups_path(@admin,work_group) %>
      <br/>
   <% end %>
 </header>

app/views/admins/work_groups.html.erb
<h1> Hiiiiiii </h1>