config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root  "employees#index"
  resources :employees do
  	resources :pay_periods
  end

  get 'create' => "employees#new"

  resource :session

  get "signin" => "sessions#new"

  resource :work_hours

  resources :admins do
    member do
      get :work_groups
      get :time_sheets
    end
  end

  get 'admins/:admin_id/work_groups/:id', to: 'admins#select_employee', as: "admin_work_groups"
  get 'admins/:admin_id/employee/:id', to: 'admins#select_pay_period', as: "select_employee_pay_period"
  resources :work_groups

  #patch 'admins/:admin_id/pay_period/:id', to: 'admins#admin_get_pay_period', as: "admin_get_pay_period"
  get 'admins/:admin_id/pay_period/:id', to: 'admins#admin_view_pay_period', as: "admin_view_pay_period"
end

app/models/pay_period.rb
class PayPeriod < ApplicationRecord
  belongs_to :employee
  has_many :work_days

  accepts_nested_attributes_for :work_days

before_update :update_daily_total

private
	def update_daily_total 
		work_days = self.work_days
			ot_total = 0
			rt_total = 0
			vt_total = 0
			sl_total = 0
			npl_total = 0 
			ml_total = 0
		
		work_days.each do |work_day|
            dt = 0
           

            dt += work_day.over_time unless work_day.over_time.nil?
            ot_total += work_day.over_time unless work_day.over_time.nil?

            dt += work_day.vacation unless work_day.vacation.nil?
            vt_total  += work_day.vacation unless work_day.vacation.nil?

            dt += work_day.regular unless work_day.regular.nil?
            rt_total += work_day.regular unless work_day.regular.nil?

            dt += work_day.maternity_leave unless work_day.maternity_leave.nil?
            ml_total += work_day.maternity_leave unless work_day.maternity_leave.nil?

            dt += work_day.non_paid_leave unless work_day.non_paid_leave.nil?
            npl_total += work_day.non_paid_leave unless work_day.non_paid_leave.nil?

            dt += work_day.sick_leave unless work_day.sick_leave.nil?
            sl_total += work_day.sick_leave unless work_day.sick_leave.nil?

            work_day.daily_total = dt 


            work_day.save
            
        end
        self.regular_total = rt_total
            self.over_time_total = ot_total
            self.vacation_total = vt_total
            self.maternity_leave_total = ml_total
            self.sick_leave_total = sl_total
            self.non_paid_leave_total = npl_total
   
	end
end

app/controllers/pay_periods_controller.rb
class PayPeriodsController < ApplicationController

	def index
        @pay_periods= @employee.pay_periods
    end    

    def show
        @employee = Employee.find(params[:employee_id])
        @pay_period = @employee.pay_periods.find(params[:id])
    end

    def new
        pay_period_attributes = params.require(:pay_period).permit(:start_date, :end_date, work_day_attributes: [:over_time] )
        @pay_period= @employee.pay_periods.new(pay_period_attributes)
    end

    def edit 
        @employee = Employee.find(params[:employee_id])
        @pay_period = @employee.pay_periods.find(params[:id])
    end

    def update
        @employee = Employee.find(params[:employee_id])
        @pay_period = @employee.pay_periods.find(params[:id])
        if @pay_period.update(pay_period_params)
         #redirect_to @pay_period, notice: "Pay Period successfully updated!"
              redirect_to edit_employee_pay_period_path(@employee, @pay_period), notice: "You've successfully updated your timesheet!"
          else
         render :edit
       end
   #pay_period_params = params.require(:pay_period).permit!
   #@pay_period.update(pay_period_params)
    end




    private
 
     def pay_period_params
 
       #params.require(:pay_period).permit(:first_name, :last_name, :hired_date, :email, :password, :password_confirmation, work_day_attributes: [:id, :over_time, :name])
         params.require(:pay_period).permit(:start_date, :end_date, work_days_attributes: [:over_time, :day, :id, :regular, :date, :sick_leave, :vacation, :maternity_leave, :non_paid_leave])

     end
end

app/helpers/pay_periods_helper.rb
module PayPeriodsHelper
	def build_dates (pay_period)
		start = Date.today 
		start + 2.week = pay_period

		
		
	end
end

app/views/pay_periods/_form.html.erb
<%= form_for(@payperiod) do |f| %>

<%#for each of the days of the week for two weeks repeat%>

  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :regular %>
        <%= f.number_field :regular, size: 2 %>
      </li>    
      <li class="required">
        <%= f.label :over_time %>
        <%= f.number_field :over_time, size: 2 %>
      </li>    
      <li class="required">
        <%= f.label :vacation %>
        <%= f.number_field :vacation, size: 2 %>
      </li>      
      <li class="required">
        <%= f.label :non_paid_leave %>
        <%= f.number_field :non_paid_leave, size: 2 %>
      </li>
      <li class="required">
        <%= f.label :sick %>
        <%= f.number_field :sick, size: 2 %>
      </li>
      <li class="required">
        <%= f.label :maternity %>
        <%= f.number_field :maternity, size: 2 %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", employee_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/pay_periods/edit.html.erb
<header>

   <%= render "shared/errors", object: @pay_period %>
<%= form_for [@employee, @pay_period] do |f| %>

   <h1><%= @employee.first_name %></h1>
   <h2> Editing Pay Period <%= @pay_period.start_date %> to <%= @pay_period.end_date %></h2>
 </div>
 <%= f.fields_for :work_days do |ff| %>

 <table>
<div class="pay-period-edit">
  <class="field">
     <%= ff.label :day %>
     <%= ff.text_field :day, class: "work-day", :readonly => true %>
      <class="field">
     <%= ff.label :date %>
     <%= ff.date_field :date, class: "work-day-date", :readonly => true %>
      <class="field">
     <%= ff.label :regular %>
     <%= ff.number_field :regular, :step=> 0.5, class: "reg-hours"%>
     <class="field">
     <%= ff.label :sick_leave %>
     <%= ff.number_field :sick_leave, :step=> 0.5, class: "reg-hours" %>
     <class="field">
     <%= ff.label :over_time %>
     <%= ff.number_field :over_time, :step=> 0.5, class: "reg-hours" %>
   <class="field">
     <%= ff.label :vacation %>
     <%= ff.number_field :vacation, :step=> 0.5, class: "reg-hours" %>
   <class="field">
     <%= ff.label :maternity_leave %>
     <%= ff.number_field :maternity_leave, :step=> 0.5, class: "reg-hours" %>
   <class="field">
     <%= ff.label :non_paid_leave %>
     <%= ff.number_field :non_paid_leave, :step=> 0.5, class: "reg-hours" %>
   <class="field">
     <%= ff.label :daily_total %>
     <%= ff.number_field :daily_total, class: "update-daily-total", :readonly => true %>
 </div>
 </table>
 <% end %>
 <hr>
 <h3> Pay Period Totals </h3>
  <class = "field">
    <%= f.label :regular_total %>
    <%= f.number_field :regular_total, class: "update-daily-total", :readonly => true %>
  <class = "field">
    <%= f.label :sick_leave_total %>
    <%= f.number_field :sick_leave_total, class: "update-daily-total", :readonly => true %>
  <class = "field">
    <%= f.label :over_time_total %>
    <%= f.number_field :over_time_total, class: "update-daily-total", :readonly => true %>
  <class = "field">
    <%= f.label :vacation_total %>
    <%= f.number_field :vacation_total, class: "update-daily-total", :readonly => true %>
  <class = "field">
    <%= f.label :maternity_leave_total %>
    <%= f.number_field :maternity_leave_total, class: "update-daily-total", :readonly => true %>
    <class = "field">
    <%= f.label :non_paid_leave_total %>
    <%= f.number_field :non_paid_leave_total, class: "update-daily-total", :readonly => true %>
 <div class="form-actions">
   <%= f.button :submit %> &nbsp &nbsp  <%= link_to "Back to my main page", employee_path(@employee) %>
 </div>
<% end %>
</div>
</header>

app/views/pay_periods/index.html.erb
<article id="employee">
  <header>
    <h1>Timesheets for: <%= @employee.first_name %> 
    	<%= @employee.last_name %></h1>
  </header>

<div class="container">
<%= form_for @employee do |f| %>

  <div class="form-group">
    <%= f.hidden_field :asdsadas, value: '123123' %>
    <%= f.label "Select Pay Period" %>
    <%= f.select :pay_periods, options_for_select(generate_pay_periods(@employee)), class: 'form-control'%>
  </div>
  <div>
    <%= f.submit 'Edit/View Timesheet', class: 'btn btn-primary btn-sm' %>
  </div>   
<% end %>
</div>

<footer>
    
    <nav>
      
    </nav>
</footer>

app/views/pay_periods/show.html.erb
<header>
  <h1>Pay Period for <%= link_to @employee.first_name, @employee %></h1>
</header>