config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root  "employees#index"
  resources :employees do
  	resources :pay_periods
  end

  get 'create' => "employees#new"

  resource :session

  get "signin" => "sessions#new"

  resource :work_hours

  resources :admins do
    member do
      get :work_groups
      get :time_sheets
    end
  end

  get 'admins/:admin_id/work_groups/:id', to: 'admins#select_employee', as: "admin_work_groups"
  get 'admins/:admin_id/employee/:id', to: 'admins#select_pay_period', as: "select_employee_pay_period"
  resources :work_groups

  #patch 'admins/:admin_id/pay_period/:id', to: 'admins#admin_get_pay_period', as: "admin_get_pay_period"
  get 'admins/:admin_id/pay_period/:id', to: 'admins#admin_view_pay_period', as: "admin_view_pay_period"
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_header.html.erb
<header id="page-header">
 <div id="masthead">
  
   <nav class="navbar navbar-default">
       <div class="navbar navbar-header">
   
   <% if current_employee %>
   <%= link_to current_employee.first_name, current_employee %> |
   <%= link_to "Account Settings", edit_employee_path(current_employee) %> |
   <%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %> 
   <%#= link_to 'Admin: Create Account', create_path, class: 'button' %>
   <% else %>
     <%= link_to 'Sign In', new_session_path, class: 'button' %> 
   <% end %>
 </div>
  <%= image_tag("ideacrew.png", size: "150x45", class: "pull-right") %>  
   </nav>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=  %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>

  <div id="wrapper">

    <%= render "layouts/flashes"  %>

    <div id="container">
      <%= render "layouts/sidebar" %>
      <section id="content">
        <%= yield %>
      </section>
    </div>

  </div>

  <%= render 'layouts/footer' %>
  </body>
</html>